[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
privment = "C3qyHGtVXDTDqKR7ng1Q4ikYK2mKxyqtZLcWpgA1fKZV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# Windows
wallet = '~\.config\solana\id.json'
# Linux
wallet = '~/.config/solana/id.json'


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"